# Generated by Django 3.2.8 on 2022-02-11 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
        ('viatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaPratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula_pratica', models.DateField()),
                ('hora_inicial', models.PositiveIntegerField(verbose_name='Hora Início')),
                ('hora_final', models.PositiveIntegerField(verbose_name='Hora Termino')),
                ('tipo_aula_pratica', models.CharField(default='Condução', max_length=10)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AulaTeorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumario', models.CharField(max_length=255)),
                ('hora_inicial', models.PositiveIntegerField(verbose_name='Hora Início')),
                ('hora_final', models.PositiveIntegerField(verbose_name='Hora Termino')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=100, verbose_name='Nome Turma')),
                ('numero_sala', models.PositiveIntegerField(verbose_name='Número Sala')),
                ('hora_inicial', models.PositiveIntegerField(verbose_name='Hora Início')),
                ('hora_final', models.PositiveIntegerField(verbose_name='Hora Termino')),
                ('max_lotacao', models.PositiveIntegerField(verbose_name='Lotação Máxima')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aula', models.CharField(choices=[('Condução', 'Condução'), ('Mecânica', 'Mecânica')], max_length=10)),
                ('dia', models.PositiveIntegerField(verbose_name='Dia')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pago', models.PositiveIntegerField(verbose_name='Total Pago')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aula', models.CharField(choices=[('Sala', 'Sala'), ('Mecânica', 'Mecânica')], max_length=10)),
                ('total_pago', models.PositiveIntegerField(verbose_name='Total Pago')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='MarcarAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aula', models.CharField(default='Condução', max_length=10)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.instrutor')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viatura.viatura')),
            ],
        ),
        migrations.CreateModel(
            name='InscreverAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aula', models.CharField(choices=[('Sala', 'Sala'), ('Mecânica', 'Mecânica')], max_length=10)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pago', models.PositiveIntegerField(verbose_name='Total Pago')),
                ('nota_pratica', models.CharField(max_length=100, verbose_name='Nota Pratica')),
                ('nota_teorica', models.CharField(max_length=100, verbose_name='Nota Teorica')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AulaTeoricaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('aulaTeorica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aula.aulateorica')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.turma')),
            ],
        ),
        migrations.AddField(
            model_name='aulateorica',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.turma'),
        ),
    ]
