# Generated by Django 3.2.8 on 2022-02-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=100)),
                ('bi', models.CharField(max_length=50, verbose_name='Bilhete de Identidade')),
                ('nacionalidade', models.CharField(max_length=150)),
                ('contacto', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Residência')),
                ('nivel_academico', models.CharField(choices=[('Tecnico Médio', 'Tecnico Médio'), ('Licenciado', 'Licenciado'), ('Mestrado', 'Mestrado'), ('Doctorado', 'Doctorado'), ('Outro', 'Outro')], max_length=100, verbose_name='Nível Academico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.pessoa')),
                ('profissao', models.CharField(max_length=150)),
            ],
            bases=('usuario.pessoa',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.pessoa')),
                ('eAdmin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('salario', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
            bases=('usuario.pessoa',),
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.funcionario')),
                ('tipo_instrutor', models.CharField(choices=[('Condução', 'Condução'), ('Aula Teorica', 'Aula Teorica')], max_length=100, verbose_name='Tipo instrutor')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
            },
            bases=('usuario.funcionario',),
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.funcionario')),
                ('tipo_mecanico', models.CharField(choices=[('Motociclo', 'Motociclo'), ('Pesado', 'Pesado'), ('Todos', 'Todos')], max_length=100)),
            ],
            options={
                'verbose_name': 'Mecânico',
                'verbose_name_plural': 'Mecânicos',
            },
            bases=('usuario.funcionario',),
        ),
    ]
