# Generated by Django 3.2.8 on 2022-02-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado_viatura', models.CharField(choices=[('Bom', 'Bom'), ('Danificado', 'Danificado'), ('Em Reparação', 'Em Reparação')], max_length=30)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
